name: Go test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
      - name: Install dependencies
        run: go get .
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2
      - name: Run golangci lint
        run: golangci-lint run
      - name: Test with the Go CLI
        run: go test -timeout 30s -race ./...